### ISSUE TITLE
humility verify

### ISSUE THREAD

**Issue by cbiffle** [oxidecomputer/humility#136]
Using the ELF images stored in the build archive, this scans read-only mappings (which are typically Flash) to see if the version in a device, or a dump, differs from the ELF file. (You'd need to skip read-write mappings because things like initialized data are _expected_ to change.)

**Comment by jclulow** [comment]
Did this end up getting prototyped?  It would be handy during manufacturing.

At present there doesn't seem to be a `humility flash --verify` or `--check` that would ensure a particular image is indeed programmed into the device.  It would help if it worked for the stage0 and image for the ROT, and the image for the SP.

I am attempting to guess based on the `*already flashed*` message that pops out of `humility flash` at the moment as to whether programming failed for a good or bad reason, and using `humility tasks idle` to try and make sure the SP image is actually there and working.
