### ISSUE TITLE
command line settings should prevail over environment variables

### ISSUE THREAD

**Issue by cbiffle** [oxidecomputer/humility#23]
I was doing a demo, and I ran

`humility diagnose`

to diagnose and capture a crashdump. I didn't need a `-a` flag because I had set `HUBRIS_ARCHIVE`.

I then attempted to display the task status from that dump:

`humility -d hubris.core.3 tasks`

And got:

```
     Running `target/debug/humility -d hubris.core.3 tasks`
error: The argument '--dump <dump>' cannot be used with '--archive <archive>'

USAGE:
    humility --archive <archive> --chip <chip> --dump <dump>

For more information try --help
```

I didn't _pass_ `--archive`, so that's confusing; moreover, this situation seems like it can be clearly resolved in favor of whatever's provided explicitly on the command line.

**Comment by bcantrill** [comment]
Indeed, annoying behavior; fixed!
