### ISSUE TITLE
Kernels have stacks too

### ISSUE THREAD

**Issue by cbiffle** [oxidecomputer/humility#29]
I'd like to implement stack analysis for the kernel. This would allow a few things:

- If we manage to catch a task that's been interrupted by an ISR, we could show that.
- If we catch a task in a syscall (far more common) we could show _that_
- If we hit a panic in the kernel we could intercept and analyze it, though we'd need breakpoint support to do this effectively.

This should not be too hard. The current stack analysis code should work correctly, just with its assumptions about the start of the stack changed. Assuming ARM-specific routines, which we currently are,

- If we're decoding a task other than the current one, just use the saved information.
- If the bottom 9 bits of xPSR are 0, don't bother. The kernel only has a stack during an interrupt. Start decoding the stack from PSP.
- If they're non-zero, start decoding from MSP. You have kernel frames while the linkage stays within the kernel RAM section, followed by task frames once we bounce over to taskyspace.
- Relying on standard frame setup preambles in kernel functions (which we generate), we should be able to tell which frames indicate entry to an ISR by inspecting the stored LR value at `[frameptr + 4]`. ISR entry uses the special `EXC_RETURN` class of LR values. The low bits of the value tell you whether code on MSP or PSP was interrupted; we can use this to identify the location of the exception frame (which will be somewhere below the frame linked to by r7).

**Comment by bcantrill** [comment]
With my apologies for having neglected to close this issue out, this was fixed in #144.
